#!/bin/sh
#
cd Canonical_Ensemble/AVB1_Methane
../../do_test
cd ../../
cd Canonical_Ensemble/Amber_Villin
../../do_test
cd ../../
#
cd Canonical_Ensemble/Benzene_AA_autofit
../../do_test
cd ../../
#
cd Canonical_Ensemble/Charmm19_ubiquitin
../../do_test
cd ../../
#
cd Canonical_Ensemble/Charmm27_benzene
../../do_test
cd ../../
#
cd Canonical_Ensemble/Charmm27_Heme
../../do_test
cd ../../
#
cd Canonical_Ensemble/Charmm27_Nucleic_Acid
../../do_test
cd ../../
#
cd Canonical_Ensemble/Charmm27_Polyalanine
../../do_test
cd ../../
#
cd Canonical_Ensemble/Compass_Methanol
../../do_test
cd ../../
#
cd Canonical_Ensemble/DREIDING
../../do_test
cd ../../
#
cd Canonical_Ensemble/FENE_Hexamer
../../do_test
cd ../../
#
cd Canonical_Ensemble/Formamide_Scaled
../../do_test
cd ../../
#
cd Canonical_Ensemble/Fris_Walls
../../do_test
cd ../../
#
cd Canonical_Ensemble/Hard_Sphere
../../do_test
cd ../../
#
cd Canonical_Ensemble/NaCl_1x1x1
../../do_test
cd ../../
#
cd Canonical_Ensemble/Shukla_Gasses
../../do_test
cd ../../
#
cd Canonical_Ensemble/Small_Peptide
../../do_test
cd ../../
#
cd Canonical_Ensemble/Square_Well_Chain
../../do_test
cd ../../
#
cd Canonical_Ensemble/TraPPE_Isomers
../../do_test
cd ../../
#
cd Canonical_Ensemble/TraPPE_Molecules
../../do_test
cd ../../
#
cd Canonical_Ensemble/Triglycerol
../../do_test
cd ../../
#
cd Canonical_Ensemble/UFF
../../do_test
cd ../../
#
cd Canonical_Ensemble/Wall_Water
../../do_test
cd ../../
#
cd Convert/LAMMPS_lc
../do_convert
cd ../../
#
cd Convert/LAMMPS_class2
../do_convert
cd ../../
#
cd Convert/LAMMPS_decane
../do_convert
cd ../../
#
cd Gibbs_Ensemble/Amber_IsoPropanol
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Catlow_Zeolite_4a
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Cu_VLE
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Cui2002_Hexane
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Dubb_Zeolite
../../do_test
cd ../../
#
cd Gibbs_Ensemble/EPM_VLCC
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Gordon
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Gromos_Isobutane
../../do_test
cd ../../
#
cd Gibbs_Ensemble/MM2_Ethane
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Potter_CF2H2
../../do_test
cd ../../
#
cd Gibbs_Ensemble/SKS_Pentane
../../do_test
cd ../../
#
cd Gibbs_Ensemble/SMMKnaip_Ethylpentane
../../do_test
cd ../../
#
cd Gibbs_Ensemble/TraPPE_Pentane
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Vink2001_Silicon
../../do_test
cd ../../
#
cd Gibbs_Ensemble/Weiner1984
../../do_test
cd ../../
#
cd Grand_Canonical_Ensemble/Amber96_Ethane
../../do_test
cd ../../
#
cd Grand_Canonical_Ensemble/Energy_Biasing
../../do_test
cd ../../
#
cd Grand_Canonical_Ensemble/Steele_Wall
../../do_test
cd ../../
#
cd Grand_Canonical_Ensemble/Walt2001_Nanotube
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Au_Cu_Switch
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Charmm22_Ethanethiol
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Cu_Pb_EAM
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Dick1994_PETN
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Gromos_Methylpropylsulfide
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Henry_Law
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Ideal_Chain
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/OPLS_Propanamide
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/SMMKmain_2244688nonane
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Solid_LJium
../../do_test
cd ../../
#
cd Isobaric_Isothermal_Ensemble/Wielop1985_Ethyleneoxide
../../do_test
cd ../../
#
cd TMMC/LJ
../../do_test
cd ../../
#
cd TMMC/SPC_E_WATER
../../do_test
cd ../../
#
cat */*/results > test_report
/bin/rm */*/results
